const GET_ALL = "GET_ALL"
const GET_COUNTRY_DETAIL_BY_ID = 'GET_COUNTRY_DETAIL_BY_ID';
const GET_COUNTRY_DETAIL_BY_STRING = 'GET_COUNTRY_DETAIL_BY_STRING';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const CREATE_ACTIVITY = "CREATE_ACTIVITY"
const CREATE_ADVANCED_ACTIVITY = "CREATE_ADVANCED_ACTIVITY"
const FILTER_CARDS = "FILTER_CARDS";
const FILTER_CARDS_BY_ACTIVITY = "FILTER_CARDS_BY_ACTIVITY"
const ORDER_CARDS = "ORDER_CARDS"
const SAVE_PERPAGE = "SAVE_PERPAGE"
const CLEAR_STATE = "CLEAR_STATE"
const API_ERROR = "API_ERROR"


module.exports = {
  GET_ALL,
  GET_COUNTRY_DETAIL_BY_ID,
  GET_COUNTRY_DETAIL_BY_STRING,
  GET_ACTIVITIES,
  CREATE_ACTIVITY,
  CREATE_ADVANCED_ACTIVITY,
  FILTER_CARDS,
  FILTER_CARDS_BY_ACTIVITY,
  ORDER_CARDS,
  SAVE_PERPAGE,
  CLEAR_STATE,
  API_ERROR,
 
}