const GET_ALL = "GET_ALL"
const GET_COUNTRY_DETAIL_BY_ID = 'GET_COUNTRY_DETAIL_BY_ID';
const GET_COUNTRY_DETAIL_BY_STRING = 'GET_COUNTRY_DETAIL_BY_STRING';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const FILTER_CARDS = "FILTER_CARDS";
const ORDER_CARDS = "ORDER_CARDS"


module.exports = {
  GET_ALL,
  GET_COUNTRY_DETAIL_BY_ID,
  GET_COUNTRY_DETAIL_BY_STRING,
  GET_ACTIVITIES,
  FILTER_CARDS,
  ORDER_CARDS,
 
}