const ADD_FAVORITE = 'ADD_FAVORITE';
const DELETE_FAVORITE = 'DELETE_FAVORITE';
const FILTER_CARDS = "FILTER_CARDS";
const ORDER_CARDS = "ORDER_CARDS"

module.exports = {
  ADD_FAVORITE,
  DELETE_FAVORITE,
  FILTER_CARDS,
  ORDER_CARDS
}